export { default as ProfileDetails } from "./components/ProfileDetails.jsx";
export { default as SideBar } from "./components/Sidebar.jsx";
export { default as Homepage } from "./pages/Homepage.jsx";
export { default as Aboutus } from "./pages/Aboutus.jsx";
export { default as Experience } from "./pages/Experience.jsx";
export { default as Specilization } from "./pages/Specilization.jsx";
export { default as MySkill } from "./pages/MySkill.jsx";
export { default as Projects } from "./pages/Projects.jsx";
export { default as ContactMe } from "./pages/ContactMe.jsx";
